import React from 'react'

function Content2() {
    return (
        <div>
            <div className="Content2" style={{padding:"20px 25px 0 25px"}}>
            <h6>Buy Electronics, Fashion, Cars & Bikes, Stationery, Daily Needs & More At Paytmmall.com: India's Premier Online Shopping Website</h6>
            <div className="para" style={{marginBottom:"10px"}}>
            <p>Say goodbye to spending hours for finding the perfect item of your choice. Just log on to Paytm Mall to discover the world of hassle-free shopping where you can shop from the comfort of your home & get your purchase delivered right at your doorstep at lightning fast speed. Whether you are looking for clothing, footwear, book, accessories, mobiles, laptops or computers, rest assured you will find it at Paytm Mall at the best price in India.</p> <br /></div>
            <div className="para" style={{marginBottom:"10px"}}>
            <p>Browse through our huge collection and pick the product of your choice at the most affordable price. From high-end products, top brands to affordable options, our varied collection makes sure that there is something for everyone and every budget type. Paytm Mall actually offers a unique combination of the mall and bazaar concept under one roof to help Indian consumers find exactly what they are looking for at the most reasonable price.</p></div>
            <div className="para" style={{marginBottom:"10px"}}>
            <p>Now, you don’t need to be living in metros to purchase the latest clothing, footwear, accessories or furniture. You can access the largest assortment of domestic and international products and get it delivered in just a few days, anywhere in India.</p><br/></div>
            <div className="para" style={{marginBottom:"10px"}}>
            <p>Whether you are looking for Men’s Fashion, Women’s Fashion or Kid’s fashion, Paytm Mall is your ultimate shopping destination. Browse through our wide selection of apparel, footwear and accessories and stay stylish and fashionable. From corporate attire, evening and party wear to casual wear, we have everything in different sizes, colors, materials & price to meet your style & requirements. Some of the key product categories at Paytm Mall include:</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}>
                <p><a href="/"><span style={{color:"#f45425"}}>Beauty & Personal Care</span></a>: Do you find it difficult to select the perfect shampoo, Perfumes & Fragrance, Body Lotion or Makeup Essentials with myriad of options available? Paytm Mall is your perfect companion when it comes to finding beauty and personal care products matching your particular skin type or style. Choose from our exhaustive collection, where each product includes information regarding skin type it’s suitable for, ingredients and usage instruction for best effect.</p><br />
            </div>
            <div className="para" style={{marginBottom:"10px"}}><p><a href="/"><span style={{color:"#f45425"}}>Home & Kitchen</span></a>: Your home & kitchen is an extension of your personality, where everything reflects your style. Choose from our wide array of products to create your dream home & kitchen, which reflects your unique taste. Avail the best deals on Home Decor & Furnishings, Cookware, Home Essentials, Wall Arts, Lamps, Clocks, to name a few.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p><a href="/"><span style={{color:"#f45425"}}>Sports & Health</span></a>: Are you a health & sport freak, then your search for gears and equipment end at Paytm Mall. From Outdoor Adventure Equipments, Swimming Gear, gym essentials to Cricket Kit, Badminton Essentials & Table Tennis Equipments, you get everything at reasonable prices under one roof.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p><a href="/"><span style={{color:"#f45425"}}>Appliances</span></a>: Get the best deals & discounts on TVs, ACs, Refrigerators, Geysers, Washing Machines and more at the Paytm Mall. We stock an assortment of electronics from various brands available at different price points. Choose electronics from brands such as Blue Star, Daikin, Haier, Hitachi, Samsung, Sony and more & get amazing cashback offers.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p><a href="/"><span style={{color:"#f45425"}}>Mobile Phones</span></a>: Now, you can flaunt the latest Smartphones & Keypad Mobiles without burning a hole in your pocket.Choose from our wide-ranging selection of smartphones and get the mobile phone of your choice at the best price in India. So, stay connected with family & friends with mobile phones from top brands, including Apple iPhone, Samsung Mobile, Oppo Mobile, Vivo Mobile, Motorola Mobile, Gionee Mobile, HTC Mobile, Micromax Mobile, Kindle and more.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p><a href="/"><span style={{color:"#f45425"}}>Laptops and Electronics</span></a>Laptops and Electronics: Check out the amazing collection of Laptops, Desktops and Computer Accessories on Paytm Mall. You can also choose from the vast assortment of Cameras, Speakers, earphones, Storage devices and avail exclusive offers. From sleek, travel-friendly laptops to sturdy business laptops with superior performance, Paytm Mall is the one-stop destination for all your needs. Also, you can choose electronics items from the most trusted brands, including Lenovo, HP, Apple, MSI, Canon, Nikon, JBL, Beats and many more.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p><a href="/"><span style={{color:"#f45425"}}>Cars & Bikes</span></a>: Enjoy the ultimate riding experience by selecting the car or bike of your dreams from the comfort of your home. Check out the exclusive range at Paytm Mall and buy car or bike loaded with features that you are looking for at the best possible price. Buy a bike or car of your choice from our portal and enjoy various Cashback offers & deals. What’s more, to make sure that our customers enjoy a seamless shopping experience, Paytm Mall allows them to book their test ride.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p><a href="/"><span style={{color:"#f45425"}}>FASTag</span></a>: FASTag is a resuable RFID Tag that all kinds of vehicle owners need to affix on the front windscreen of their vehicle, as it will make your highway experience smoother. Now, you don’t have to carry cash to pay toll charges, as toll amount is deducted automatically from the linked FASTag wallet.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p>Gone are the days, when we had to go to different shops or even different markets for purchasing our favourite products at reasonable prices. All this has changed, as just about anything can be bought online that too at amazingly discounted prices. And to make the deals even more lucrative for you Paytm Mall has come up with its Happy New Year Sale. This sale consists of The Gift Gallery, 2019 Trendy Must Haves, and Deals Starting at ?1, Clearance Deals 2018 and Cracking Combos accompanied by a variety of other products that we need on a regular basis.</p><br /></div>
            <h6 style={{color:"#676769",fontWeight:"bold"}}>Shop for the Newly Launched Mobiles At Exclusive Prices Online at Paytm Mall</h6>
            <div className="para" style={{marginBottom:"10px"}}><p>Mobile phones have become an integral part of our lives. It becomes essential to have the latest smartphone to keep up with the ever-evolving world of technology. Paytm Mall brings to you the latest assortment of best smartphones in India from the leading mobile makers such as Apple, Samsung, Vivo, Oppo and many more! Buy latest smartphones from Paytm Mall and avail heavy Cashback offers available exclusively with us.</p><br /></div>
            <h6 style={{fontWeight:"bold"}}>Paytm Mall: Re-defining Your Shopping Experience</h6>
            <div className="para" style={{marginBottom:"10px"}}><p>No matter what product you are looking for, get ready to be spoilt for choices at Paytm Mall. Apart from our massive selection, there are numerous other perks of buying from Paytm Mall. Being your trusted online shopping partner, we offer services like doorstep delivery, quick refunds, cash on delivery, and easy & secured payment options.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p>When you shop from Paytm Mall, you are assured the get the product of top quality as we conduct stringent quality checks right from storage to delivery. Also, we list structured categories and only authorized brands. While we make sure that your purchase reaches you at the earliest, we also make sure that it reaches you in the best condition as it goes through our certified warehouse and shopping channel.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p>Customer satisfaction is key to us. So, if the delivered product is not how you expected or doesn’t fit you properly, don’t worry. Thanks to our easy return policy, you can send the piece back.</p><br /></div>
            <div className="para" style={{marginBottom:"10px"}}><p>So, what are you waiting for, download Paytm Mall App from App Store available for iOS, Android & Windows to avail the best discounts & deals!</p><br /></div>
            </div>
        </div>
    )
}

export default Content2
